region: eu-central-1
metrics:
  - aws_namespace: AWS/ECS
    aws_metric_name: hello_world_cpu
    aws_dimensions: [ClusterName, ServiceName]
    aws_statistics: [Average]
    period_seconds: 60
  - aws_namespace: AWS/ECS
    aws_metric_name: hello_world_memory
    aws_dimensions: [ClusterName, ServiceName]
    aws_statistics: [Average]
    period_seconds: 60
  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: RequestCount
    aws_dimensions: [LoadBalancer]
    aws_statistics: [Sum]
    period_seconds: 60
  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: HTTPCode_ELB_4XX_Count
    aws_dimensions: [LoadBalancer]
    aws_statistics: [Sum]
    period_seconds: 60