version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.46.0
    restart: always
    volumes:
      - /srv/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /srv/prometheus/prometheus_data:/prometheus
    command: >
      --config.file=/etc/prometheus/prometheus.yml
      --storage.tsdb.path=/prometheus
      --web.console.libraries=/etc/prometheus/console_libraries
      --web.console.templates=/etc/prometheus/consoles
      --web.enable-lifecycle
      --storage.tsdb.retention.time=1y
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.0.3
    restart: always
    volumes:
      - /srv/grafana:/var/lib/grafana
      - /srv/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_PATHS_DATA=/var/lib/grafana
    ports:
      - "3000:3000"

  cloudwatch-exporter:
    image: prom/cloudwatch-exporter:v0.15.5
    restart: always
    volumes:
      - /srv/exporter/config.yml:/config/config.yml
    environment:
      - AWS_ACCESS_KEY_ID=<>
      - AWS_SECRET_ACCESS_KEY=<>
    ports:
      - "9106:9106"